org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# If your system Java is v11 but the Android Gradle Plugin / Gradle wrapper
# require Java 17, you can point Gradle to a specific JDK installation by
# uncommenting and setting `org.gradle.java.home` below to your JDK 17 path.
# Example (Windows):
# org.gradle.java.home=C:\\Program Files\\Java\\jdk-17
# Example (macOS / Linux):
# org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home

