import 'dart:convert';

/// ===============================================================
/// Embedding Model
/// ===============================================================
///
/// Represents one facial embedding stored in SQLite.
///
/// One user has FIVE embeddings:
///
/// - front
/// - left
/// - right
/// - up
/// - down
///
/// Embeddings are stored separately from the users table.
///
/// The embedding vector is serialized as JSON.
/// ===============================================================

class EmbeddingModel {
  final int? id;

  /// Foreign key -> users.user_id
  final String userId;

  /// front / left / right / up / down
  final String pose;

  /// Face embedding generated by the TFLite model.
  final List<double> embedding;

  final DateTime createdAt;

  const EmbeddingModel({
    this.id,
    required this.userId,
    required this.pose,
    required this.embedding,
    required this.createdAt,
  });

  /// -------------------------------------------------------------
  /// Copy
  /// -------------------------------------------------------------
  EmbeddingModel copyWith({
    int? id,
    String? userId,
    String? pose,
    List<double>? embedding,
    DateTime? createdAt,
  }) {
    return EmbeddingModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      pose: pose ?? this.pose,
      embedding: embedding ?? this.embedding,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  /// -------------------------------------------------------------
  /// SQLite
  /// -------------------------------------------------------------
  Map<String, dynamic> toMap() {
    return {
      "id": id,
      "user_id": userId,
      "pose": pose,
      "embedding": jsonEncode(embedding),
      "created_at": createdAt.toIso8601String(),
    };
  }

  factory EmbeddingModel.fromMap(Map<String, dynamic> map) {
    return EmbeddingModel(
      id: map["id"] as int?,
      userId: map["user_id"] as String,
      pose: map["pose"] as String,
      embedding: List<double>.from(
        (jsonDecode(map["embedding"]) as List).map(
          (e) => (e as num).toDouble(),
        ),
      ),
      createdAt: DateTime.parse(map["created_at"] as String),
    );
  }

  /// -------------------------------------------------------------
  /// JSON
  /// -------------------------------------------------------------
  String toJson() => jsonEncode(toMap());

  factory EmbeddingModel.fromJson(String source) {
    return EmbeddingModel.fromMap(jsonDecode(source) as Map<String, dynamic>);
  }

  /// -------------------------------------------------------------
  /// Helper
  /// -------------------------------------------------------------
  int get dimension => embedding.length;

  bool get isValid => embedding.isNotEmpty;

  /// -------------------------------------------------------------
  /// Equality
  /// -------------------------------------------------------------
  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is EmbeddingModel &&
        other.id == id &&
        other.userId == userId &&
        other.pose == pose &&
        _listEquals(other.embedding, embedding) &&
        other.createdAt == createdAt;
  }

  @override
  int get hashCode {
    return Object.hash(id, userId, pose, Object.hashAll(embedding), createdAt);
  }

  @override
  String toString() {
    return '''
EmbeddingModel(
  id: $id,
  userId: $userId,
  pose: $pose,
  dimension: ${embedding.length},
  createdAt: $createdAt
)
''';
  }

  static bool _listEquals(List<double> a, List<double> b) {
    if (a.length != b.length) return false;

    for (int i = 0; i < a.length; i++) {
      if (a[i] != b[i]) {
        return false;
      }
    }

    return true;
  }
}
